package com.example.tangochoupdated.db.enumclass


enum class ActivityStatus {
    FILE_CREATED,
    FILE_TITLE_EDITED,
    FILE_DELETED,

    CARD_CREATED,
    CARD_EDITED,
    CARD_SAFE_DELETED,

    CARD_LOOKED,
    RIGHT_CHOICE_SELECTED,
    WRONG_CHOICE_SELECTED,
    RIGHT_FRONT_CONTENT_TYPED,
    WRONG_FRONT_CONTENT_TYPED,
    RIGHT_BACK_CONTENT_TYPED,
    WRONG_BACK_CONTENT_TYPED,

    CARD_REMEMBERED,
    CARD_FORGOT,

    RIGHT_MARKER_WORD_TYPED,
    WRONG_MARKER_WORD_TYPED,
    MARKER_WORD_REMEMBERED,
    MARKER_WORD_FORGOT,

}
